repository_type: pipeline
nf_core_version: "3.3.1"
lint:
  files_exist:
    - assets/nf-core-snvphylnfc_logo_light.png
    - docs/images/nf-core-snvphylnfc_logo_light.png
    - docs/images/nf-core-snvphylnfc_logo_dark.png
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - lib/Utils.groovy
    - lib/WorkflowMain.groovy
    - lib/NfcoreTemplate.groovy
    - lib/WorkflowSnvphylnfc.groovy
    - conf/igenomes_ignored.config
    - ro-crate-metadata.json
    - .github/workflows/nf-test.yml
    - .github/actions/get-shards/action.yml
    - .github/actions/nf-test/action.yml
    - tests/default.nf.test
  files_unchanged:
    - assets/sendmail_template.txt
    - assets/email_template.html
    - lib/NfcoreTemplate.groovy
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
    - assets/email_template.txt
    - docs/README.md
    - LICENSE
    - .gitignore
  pipeline_name_conventions: False
  actions_awsfulltest: False
  multiqc_config:
    - report_comment
  nextflow_config:
    - custom_config
    - manifest.name
    - manifest.homePage
    - params.max_cpus
    - params.max_memory
    - params.max_time
  readme:
    - nextflow_badge
